### ISSUE TITLE
Additional 12x12's for you.

### ISSUE THREAD

**Issue by clort81** [vurmux/urizen#11]
Hello,

I'm also making 1bit 6x12 and 12x12, and 18x12 etc sprites for inclusion in a gaming-font for terminals. I love some of your sprites here.

I'm not convinced copyright is enforceable on 12x12 pixmaps but my work is declared CC0.  You may use any of these or just take ideas.

[6x12_font_PUA_bitmaps_2023_06.zip](https://github.com/vurmux/urizen/files/11800025/6x12_font_PUA_bitmaps_2023_06.zip)

If I use some of your sprites what is your preferred attribution and name?  E.g. "Includes sprites from urizen by vurmux."

**Comment by vurmux** [comment]
Hello!
Thank you for sharing. I will take some ideas from this tileset. But I prefer to draw tiles by myself, so I will not use tiles as is.
My tileset is under CC0 too. You can re-use it for free. If you will use tiles as is, I will be appreciated if you will write credits like "Includes sprites from Urizen 1Bit Tileset by vurmux". But if you want, you can use them without credits.
