### ISSUE TITLE
Question about Google Collaboratory

### ISSUE THREAD

**Issue by Tazshelby2016** [vurmux/urizen#9]
Would you be able to run these programs in Google Collaboratory?

**Comment by vurmux** [comment]
As I understand, Google Collaboratory works around Jupyter notebooks. You can run it inside and visualize maps with parameter `show=False` to prevent an image from be opened in the external image viewer, which forces Jupyter to show an image inside the notebook.

**Comment by Tazshelby2016** [comment]
I still do not understand how to use this in Google Collaboratory. Is the process any different than doing it elsewhere? I cannot build any programs through command-line tools other than Google Collaboratory.

**Comment by Tazshelby2016** [comment]
Turns out Google Collaboratory does properly generate the image when I use the `vg_tiled` command. However, Google Collaboratory does not render the image, so I am still trying to find a way to view the image.

**Comment by Tazshelby2016** [comment]
Found it!
``` python
!pip install urizen
import urizen as uz
from PIL import Image
Map = uz.building_ruined_house(w=9, h=9)
a = uz.vg_tiled(Map, scale=10, show=False, filepath=None)
a.save(fp= 'name.png', format=None)

```
